### ISSUE TITLE
Rename to "shipstation"?

### ISSUE THREAD

**Issue by csexton** [codyduval/shipstation-ruby#6]
Cody, thanks for this gem, it is really helpful.

I was wondering if you were interested in me updating a few things to make it a little more idiomatic for ruby. I'd be happy to do the changes, but wanted to discuss with you to see if you'd like to integrate them upstream in your project.

The biggest and the one that will break things is renaming the gem to be just "shipstation." I thought it would be cleaner and more obvious. FWIW, I did get hung up on requiring it initially where I used a dash instead of an underscore.

Again, thanks for the library.

**Comment by codyduval** [comment]
@csexton, absolutely.  As you can tell, this gem has been sitting fallow for some time and any attention would be appreciated.  Fork away and I'll merge as needed.

Thanks!
